app.py
import logging
import os
from logging.handlers import RotatingFileHandler
from importlib import import_module

import jinja2
from flask import (Flask, g, redirect, render_template, request, url_for,
                   Blueprint, Response)
from flask_babel import (Babel, _)
from flask_caching import Cache
from flask_mobility import Mobility
from jinja2 import filters
from flask_mail import Mail, Message
from flask_apscheduler import APScheduler

import config
from models import db
from views.admin import admin
from services.translator import get_translated

app = Flask(config.APP_NAME)
app.config.from_object(config)
app.config.from_pyfile(os.environ.get('APP_CONFIG', 'config.cfg'), silent=True)

main = Blueprint('main', 'main')
db.init_app(app)
admin.init_app(app)
cron = APScheduler()
babel = Babel(app)
Mobility(app)
cache = Cache(app, config=app.config)
setattr(app, 'cache', cache)
mail = Mail(app)


# logging
class FlaskMailLogHandler(logging.Handler):
    def __init__(self, mail, recipients, *args, **kwargs):
        super(FlaskMailLogHandler, self).__init__(*args, **kwargs)
        self.mail = mail
        self.recipients = recipients

    def emit(self, record):
        self.mail.send(Message(
            recipients=self.recipients,
            body=self.format(record),
            subject=f'{config.APP_NAME} ERROR!'))


if not app.debug:
    formatter = logging.Formatter(app.config['LOG_FORMAT'])
    handler = RotatingFileHandler(app.config['LOG_PATH'],
                                  maxBytes=1000000, backupCount=1)
    handler.setFormatter(formatter)
    app.logger.addHandler(handler)
    handler.setLevel(logging.INFO)
    mail_handler = FlaskMailLogHandler(mail, app.config['ADMINS'])
    mail_handler.setLevel(logging.ERROR)
    mail_handler.setFormatter(formatter)
    app.logger.addHandler(mail_handler)


def mail_alert(text):
    mail.send(Message(
        recipients=app.config['ADMINS'],
        body=text,
        subject=f'{config.APP_NAME} ALERT!'))


# localization
month_abbr = ['', 'січ', 'лют', 'бер', 'кві', 'тра', 'чер', 'лип', 'сер',
              'вер', 'жов', 'лис', 'гру']


@babel.localeselector
def get_locale():
    return g.get('lang', app.config['BABEL_DEFAULT_LOCALE'])


@app.url_defaults
def set_language_code(endpoint, values):
    if 'lang' in values or not g.get('lang', None):
        return
    if app.url_map.is_endpoint_expecting(endpoint, 'lang'):
        values['lang'] = g.lang
    pass


@app.url_value_preprocessor
def get_lang_code(endpoint, values):
    if values is not None:
        lang = values.get('lang', None)
        if lang in app.config['SUPPORTED_LANGUAGES'].keys():
            g.lang = values.pop('lang', None)


@app.before_request
def ensure_lang_support():
    lang = g.get('lang', None)
    if lang not in app.config['SUPPORTED_LANGUAGES'].keys():
        g.lang = app.config['BABEL_DEFAULT_LOCALE']


# context filters

@jinja2.contextfilter
@app.template_filter(name='month_abbr')
def month_filter(context, value):
    return month_abbr[value]


@jinja2.contextfilter
@app.template_filter(name='color')
def number_color(context, value):
    if value > 0:
        value = f'<p style="color:green">+{value}</p>'
    elif value < 0:
        value = f'<p style="color:red">{value}</p>'
    else:
        return value
    return filters.do_mark_safe(value)


# custom template context
def translate_name(text):
    @cache.memoize(timeout=24 * 60 * 60)
    def _translate(_text, lang):
        return get_translated(_text, lang)

    return _translate(text, g.get('lang', app.config['BABEL_DEFAULT_LOCALE']))


def translate_array(arr):
    return [translate_name(_(x)) for x in arr]


def url_for_other_page(page):
    args = request.view_args.copy()
    args.update(request.args)
    args['page'] = page
    return url_for(request.endpoint, **args)


@app.context_processor
def dynamic_translate_processor():
    return dict(name=translate_name,
                translate_arr=translate_array,
                url_for_other_page=url_for_other_page)


@app.context_processor
def form_parameters():
    return {k: request.args.get(k) for k in request.args}


# base routes
@main.route('/about/')
def about():
    return render_template('about.html')


@app.route('/')
def home():
    return redirect(url_for(f'{app.config["HOME_PAGE"]}'))


@app.errorhandler(404)
def page_not_found(e):
    return render_template('404.html'), 404


@app.errorhandler(500)
def internal_server_error(e):
    return render_template('500.html'), 500


@app.before_first_request
def start_cron():
    cron.init_app(app)  # init scheduler
    cron.start()


@app.before_request
def basic_auth():
    if request.path.startswith('/admin') or \
            request.path.startswith('/scheduler'):
        auth = request.authorization
        if not auth or not (auth.username == app.config['ADMIN_USERNAME']
                            and auth.password == app.config['ADMIN_PASS']):
            return Response(
                '<Not public access...>', 401,
                {'WWW-Authenticate': 'Basic realm="Login Required"'})


def load_modules():
    import_module('cli')  # init commands

    app.register_blueprint(main, url_prefix='/<lang>')
    app.register_blueprint(main, url_prefix='')

    for _module in app.config.get('BLUEPRINTS', []):
        bp = import_module(_module).bp
        app.register_blueprint(bp, url_prefix='/<lang>')
        app.register_blueprint(bp, url_prefix='')

views/rating.py
import json
from flask import abort, g, request, url_for, Blueprint
from sqlalchemy.orm import eagerload
from services.games_chain import find_chain
import models as m
from app import cache, render_template, month_abbr
from services.translator import search_translations
from views.common import cities, get_rating_lists, get_years, translate_name
from flask_mobility.decorators import mobile_template

bp = Blueprint('rating', __name__)


@bp.route('/rating/<category>/')
@bp.route('/rating/')
@mobile_template('{mobile/}rating/rating.html')
@cache.cached(key_prefix=lambda: request.url + str(request.MOBILE))
def rating(template, category='MEN'):
    rating_lists = get_rating_lists()
    year = request.args.get('year', rating_lists[0].year, type=int)
    month = request.args.get('month', rating_lists[0].month, type=int)
    page = request.args.get('page', 1, type=int)
    limit = request.args.get('limit', 25, type=int)
    sort_by = request.args.get('sort', 'position')
    city = request.args.get('city', 'all cities')
    if request.args.get('desc', False, type=bool):
        sort_by += ' desc'

    years = get_years()
    rating = m.Rating.query.join(m.Player).options(
        eagerload('player')).filter(
        m.Rating.year == year,
        m.Rating.month == month,
        m.Player.category == category,
        m.Rating.rating >= 10).order_by(m.Rating.position)
    if city != 'all cities':
        rating = rating.filter(m.Player.city == city)
    rating = rating.paginate(per_page=limit, page=page)
    date = f'{month_abbr[month]} {year}'

    return render_template(template, rating=rating,
                           categories=m.Category.VALUES, category=category,
                           date=date, year=year, month=month, years=years,
                           city=city, cities=cities())


@bp.route('/player/<id>/')
@mobile_template('{mobile/}rating/player.html')
@cache.cached(key_prefix=lambda: request.url + str(request.MOBILE))
def player(template, id):
    player = m.Player.query.get(id)
    if not player:
        abort(404)
    ratings = m.Rating.query.filter_by(player_id=id).order_by(
        m.Rating.year, m.Rating.month).all()
    ratings_values = [r.rating for r in ratings]
    weight_values = [r.weight for r in ratings]
    position_values = [r.position for r in ratings]
    dates = [f'{month_abbr[r.month]} {r.year}' for r in
             ratings]
    return render_template(template, player=player,
                           ratings=ratings_values, weights=weight_values,
                           positions=position_values, dates=dates)


@bp.route('/player-tournament/<int:player_id>/<int:tournament_id>/')
@mobile_template('{mobile/}rating/player_tournament.html')
@cache.cached(key_prefix=lambda: request.url + str(request.MOBILE))
def player_tournament(template, player_id, tournament_id):
    player_tournament = m.PlayerTournament.query.filter_by(
        player_id=player_id, tournament_id=tournament_id).first()
    return render_template(template, player_tournament=player_tournament)


@bp.route('/tournament/<int:id>/')
@mobile_template('{mobile/}rating/tournament.html')
@cache.cached(key_prefix=lambda: request.url + str(request.MOBILE))
def tournament(template, id):
    tournament = m.Tournament.query.get(id)
    return render_template(template, tournament=tournament)


@bp.route('/tournaments/<int:year>/<int:month>/')
@bp.route('/tournaments/')
@mobile_template('{mobile/}rating/tournaments.html')
@cache.cached(key_prefix=lambda: request.url + str(request.MOBILE))
def tournaments(template, year=None, month=None):
    years = get_years()
    if not year:
        year = get_rating_lists()[0].year
    if not month:
        month = get_rating_lists()[0].month
    rating_list = m.RatingList.query.filter_by(year=year, month=month).first()
    if not rating_list:
        tournaments = []
    else:
        tournaments = m.Tournament.query.filter_by(
            rating_list_id=rating_list.id).order_by(
            m.Tournament.start_date.desc()).all()
    return render_template(template, tournaments=tournaments,
                           year=year, month=month, years=years)


@bp.route('/win-chain/')
@mobile_template('{mobile/}rating/win_chain.html')
@cache.cached(key_prefix=lambda: request.url + str(request.MOBILE))
def win_chain(template):
    player1_id = request.args.get('player1_id', type=int)
    player2_id = request.args.get('player2_id', type=int)
    count_all = request.args.get('count_all', type=bool, default=False)

    chain = []
    player1 = None
    player2 = None
    if player1_id and player2_id:
        player1 = m.Player.query.get(player1_id)
        player2 = m.Player.query.get(player2_id)
        chain = find_chain(player1_id, player2_id, all=count_all)
    return render_template(template, player1=player1, player2=player2,
                           chain=chain, count_all=count_all)


@bp.route('/games/')
@mobile_template('{mobile/}rating/games_search.html')
@cache.cached(key_prefix=lambda: request.url + str(request.MOBILE))
def game_search(template):
    player1 = request.args.get('player1', '')
    player2 = request.args.get('player2', '')
    player1_id = request.args.get('player1_id')
    player2_id = request.args.get('player2_id')
    page = request.args.get('page', 1, type=int)
    filters = []
    if player1_id:
        filters.append(m.Game.player_id == player1_id)
    elif player1:
        filters.append(m.Game.player_name.like("%" + player1.title() + "%"))
    if player2_id:
        filters.append(m.Game.opponent_id == player2_id)
    elif player2:
        filters.append(m.Game.opponent_name.like("%" + player2.title() + "%"))
    games = None
    if filters:
        games = m.Game.query.join(m.Tournament).filter(*filters).order_by(
            m.Tournament.start_date.desc()).paginate(page=page, per_page=25)
    return render_template(template, games=games, player1=player1,
                           player2=player2, player1_id=player1_id,
                           player2_id=player2_id)


@bp.route('/statistics/')
@mobile_template('{mobile/}rating/statistics.html')
@cache.cached(key_prefix=lambda: request.url + str(request.MOBILE))
def statistics(template):
    page = request.args.get('page', 1, type=int)
    issues = m.TopicIssue.query.join(m.Topic).options(
        eagerload('topic')).order_by(m.TopicIssue.new).order_by(
        m.Topic.index).filter(m.Topic.active).paginate(per_page=7, page=page)
    return render_template(template, issues=issues)


@bp.route('/player-search/<name>')
@cache.cached()
def player_search(name):
    if g.lang == 'ru':  # default player name language
        matches = m.Player.query.filter(
            m.Player.name.like('%' + name.title() + '%')).limit(10).all()
    else:
        translations = search_translations(name.title(), g.lang)
        matches = m.db.session.query(m.Player).filter(
            m.Player.name.in_(translations)).limit(10).all()
    return json.dumps([{'name': translate_name(p.name),
                        'rating': p.rating or '0.0',
                        'url': url_for('.player', id=p.id),
                        'city': translate_name(p.city),
                        'year': p.year,
                        'id': p.id,
                        'image': p.photo_url}
                       for p in matches])

views/subscribers.py
from flask import current_app as app
import datetime
from flask import request, render_template, abort, Blueprint, redirect, \
    url_for, g
from app import mail, db, mail_alert
import models as m
from flask_mail import Message
from flask_babel import _
from itsdangerous import URLSafeTimedSerializer, URLSafeSerializer
import config

bp = Blueprint('subscribe', __name__)


def generate_confirmation_token(email):
    serializer = URLSafeTimedSerializer(app.config['SECRET_KEY'])
    return serializer.dumps(email, salt=app.config['SECURITY_PASSWORD_SALT'])


@bp.route('/subscribe', methods=['GET', 'POST'])
def subscribe():
    if request.method == 'GET':
        accepted = request.args.get('accepted')
        return render_template('subscribe.html', accepted=accepted == 'True',
                               errors={})
    else:
        password = request.form.get('password')
        player_id = request.form.get('player_id')
        email = request.form.get('email')
        language = g.lang
        errors = {}
        # validate
        if m.User.query.filter_by(email=email).first():
            errors['email'] = 'Такий email вже зареєстровано!'
        if len(password) < 6:
            errors['password'] = 'Пароль занадто короткий, мінімум 6 символів'

        if errors:
            return render_template('subscribe.html', errors=errors)

        user = m.User(email, password, confirmed=False, player_id=player_id,
                      confirmed_on=datetime.datetime.now(), language=language)
        token = generate_confirmation_token(email)
        db.session.add(user)
        db.session.commit()
        msg = Message(subject=f'Subscribe {config.APP_NAME}',
                      html=render_template('email/subscribe_confirm.html',
                                           token=token, user=user),
                      recipients=[email])
        mail.send(msg)
        return redirect(url_for('.subscribe', accepted=True))


@bp.route('/subscribe/confirm/<token>')
def confirm(token):
    if request.args.get('confirmed'):
        render_template('subscribe.html', confirmed=True)
    serializer = URLSafeTimedSerializer(app.config['SECRET_KEY'])
    try:
        email = serializer.loads(
            token,
            salt=app.config['SECURITY_PASSWORD_SALT'],
            max_age=24 * 3600
        )
        user = m.User.query.filter_by(email=email).first_or_404()
        user.confirmed = True
        user.confirmed_on = datetime.datetime.now()
        db.session.add(user)
        db.session.commit()
        mail_alert(f'New subscribe - {email}!')
        return redirect(url_for('.subscribe', confirmed=True))

    except Exception as e:
        app.logger.error(f'Failed to confirm email. Reason: {e}')
        raise e


@bp.route('/unsubscribe/<token>')
def unsubscribe(token):
    s = URLSafeSerializer(app.secret_key, salt='unsubscribe')

    try:
        email = s.loads(token)
        m.User.query.filter_by(email=email).delete()
        return _("Ви відписались від оновлень")
    except Exception as e:
        app.logger.error(f'Failed to get email on unsubscibe. Reason: {e}')
        abort(404)

templates/about.html
{% extends "index.html" %}
{% block title %}{{ _('Про сайт') }}{% endblock %}
{% block head %}
    {{ super() }}
{% endblock %}
{% block content %}
    {{ super() }}
    <div class="ui text container">
        <h3>{{ _('Про сайт') }}:</h3>
        <p>
            {% if g.lang == 'ru' %}
                Сайт использует информацию с ресурсов
                <a href="http://reiting.com.ua">reiting.com.ua</a> и
                <a href="http://old.ittf.com">old.ittf.com</a>. А также
                некоторые изображения взяты с ресурса
                <a href="http://tt-cup.com">tt-cup.com</a>.
            {% endif %}
            {% if g.lang == 'uk' %}
                Cайт використовує інформацію с сайтів
                <a href="http://reiting.com.ua">reiting.com.ua</a> (український
                рейтинг) і
                <a href="http://old.ittf.com">old.ittf.com</a> (Світовий
                рейтинг). А також
                деякі зображення взяті з ресурсу
                <a href="http://tt-cup.com">tt-cup.com</a>.
            {% endif %}
            {% if g.lang == 'en' %}
            {% endif %}
        </p>
    </div>
{% endblock %}

templates/base.html
<!doctype html>
<html>
<head>
    {% block head %}
        <link rel="stylesheet"
              href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.9/semantic.min.css">

        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>

        <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.9/semantic.min.js"></script>
        <link rel="icon" href="/static/img/logo.png">
        <meta property="og:image" content="/static/img/logo.png"/>
        <meta name="keywords" content="{{ config.PAGE_META_KEYWORDS }}">
        <meta name="description" content="{{ config.PAGE_META_DESCRIPTION }}">
        <title>{% block title %}{% endblock %} - TTennis</title>
    {% endblock %}
</head>
<body>
<div id="content">{% block content %}{% endblock %}</div>
<div id="footer" class="footer-right">
    {% block footer %}
        <div class="ui divider"></div>
        <div class="ui footer">
            <div class="ui three column grid">
                <div class="column" align="center">
                    @ 2017 <a
                        href="{{ url_for('main.about') }}">{{ config.BRAND }}</a>
                    <div>{{ _('Рейтинги взяті з сайту') }}
                        <a href="http://reiting.com.ua/"
                           target="_blank">reiting.com.ua</a>
                    </div>
                    <!--language selection-->
                </div>
                <div class="column" align="center">
                    {% for i, name in config.SUPPORTED_LANGUAGES.items() %}
                        {% if i == g.lang %}
                            <a class="item"
                               href="{{ request.url.replace('/%s/' % g.lang,'/%s/' % i) }}">
                                {{ name }}</a> ·
                        {% else %}
                            <a class="active item" style="color: darkgrey"
                               href="{{ request.url.replace('/%s/' % g.lang,'/%s/' % i) }}">
                                {{ name }}</a> ·
                        {% endif %}
                    {% endfor %}
                    <div>
                        {# vk share  #}
                        <a href="{{ 'http://vkontakte.ru/share.php?title=' + _(config.APP_DESCRIPTION) + '&url=' + request.url.replace('&','%26') + '&amp' }}"><i
                                class="large vk icon"></i></a>
                        {# facebook share  #}
                        <a href="{{ 'http://www.facebook.com/sharer.php?s=100&p[title]=' + _(config.APP_DESCRIPTION) + '&p[url]=' + request.url.replace('&','%26') }}"><i
                                class="large facebook icon"></i></a>
                        {# twitter share  #}
                        <a href="{{ 'http://twitter.com/share?url=' + request.url.replace('&','%26') + '&test=' + _(config.APP_DESCRIPTION) }}"><i
                                class="large twitter icon"></i></a></div>
                </div>
                <div class="column" align="center">
                    <strong>{{ _('Контакти') }}:</strong>
                    <p><i class="mail icon"></i>{{ config.EMAIL }}</p>
                </div>
            </div>
            <a style="position: fixed; right:15px;top :15px; z-index: 1000"
               href="{{ url_for('subscribe.subscribe') }}"
               data-content="{{ _('Subscribe on rating update!') }}"><i
                    class="ui big bell outline icon"></i></a>
        </div>
    {% endblock %}
</div>
</body>
</html>

templates/filters.html
{% filter number_color %}
    This text becomes uppercase
{% endfilter %}

templates/index.html
{% extends "base.html" %}
{% block title %}{% endblock %}
{% block head %}
    {{ super() }}

    {% if config.SERVER_NAME == 'ttennis.life' %}
        <script>
            (function (i, s, o, g, r, a, m) {
                i['GoogleAnalyticsObject'] = r;
                i[r] = i[r] || function () {
                        (i[r].q = i[r].q || []).push(arguments)
                    }, i[r].l = 1 * new Date();
                a = s.createElement(o),
                    m = s.getElementsByTagName(o)[0];
                a.async = 1;
                a.src = g;
                m.parentNode.insertBefore(a, m)
            })(window, document, 'script', 'https://www.google-analytics.com/analytics.js', 'ga');

            ga('create', 'UA-99396093-1', 'auto');
            ga('send', 'pageview');

        </script>
    {% endif %}

    <script>
        $(document)
            .ready(function () {

                // init ui elements
                $('.ui.dropdown').dropdown();
                $('.popup').popup();
                $('.message .close').on('click', function () {
                    $(this).closest('.message').transition('fade')
                });
                $('.accordion').accordion();

                // fix main menu to page on passing
                $('.main.menu').visibility({
                    type: 'fixed'
                });
                $('.overlay').visibility({
                    type: 'fixed',
                    offset: 80
                });
            })
        ;
    </script>

    <style type="text/css">
        body {
            background-color: #ffffff;
            display: flex;
            min-height: 100vh;
            flex-direction: column;
        }

        #content {
            flex: 1;
        }

        .main.container {
            margin-top: 2em;
        }

        .main.menu {
            margin-top: 4em;
            border-radius: 0;
            border: none;
            box-shadow: none;
            transition: box-shadow 0.5s ease,
            padding 0.5s ease;
        }

        .main.menu .item img.logo {
            margin-right: 1.5em;
        }

        .overlay {
            float: left;
            margin: 0em 3em 1em 0em;
        }

        .overlay .menu {
            position: relative;
            left: 0;
            transition: left 0.5s ease;
        }

        .main.menu.fixed {
            background-color: #FFFFFF;
            border: 1px solid #DDD;
            box-shadow: 0px 3px 5px rgba(0, 0, 0, 0.2);
        }

        .overlay.fixed .menu {
            left: 800px;
        }

        img {
            filter: grayscale(100%);
        }

        img:hover {
            filter: none;
        }
    </style>
{% endblock %}
{% block content %}
    <div class="ui main text container">
        <h2 class="ui header">{{ _('Настільний теніс України') }}</h2>
        <p>{{ _('Рейтинги, турніри, статистика і багато іншого') }}</p>
    </div>
    <div class="ui borderless main menu">
        <div class="ui text container">
            <div class="header item">
                <img class="logo" src="/static/img/logo.png">
                {{ config.BRAND }}
            </div>
            <a href="{{ url_for('rating.statistics') }}"
               class="{% if '.statistics' in request.endpoint %}active{% endif %} item">
                {{ _('Статистика') }}</a>
            <a href="{{ url_for('rating.rating') }}"
               class="{% if '.rating' in request.endpoint %}active{% endif %} item">
                {{ _('Рейтинг') }}</a>
            <a href="{{ url_for('rating.tournaments') }}"
               class="{% if '.tournaments' in request.endpoint %}active{% endif %} item">
                {{ _('Турніри') }}</a>
            <div class="ui right floated dropdown item">
                {{ _('Меню') }} <i class="dropdown icon"></i>
                <div class="menu">
                    {% if 'views.rating' in config.BLUEPRINTS %}
                        <a href="{{ url_for('rating.statistics') }}"
                           class="{% if '.statistics' in request.endpoint %}active{% endif %} item">
                            <i class="bar chart icon"></i>
                            {{ _('Статистика') }}</a>
                        <a href="{{ url_for('rating.rating') }}"
                           class="{% if '.rating' in request.endpoint %}active{% endif %} item">
                            <i class="table icon"></i>
                            {{ _('Рейтинг') }}</a>
                        <a href="{{ url_for('rating.tournaments') }}"
                           class="{% if '.tournaments' in request.endpoint %}active{% endif %} item">
                            <i class="trophy icon"></i>
                            {{ _('Турніри') }}</a>
                        <a href="{{ url_for('rating.game_search') }}"
                           class="{% if   '.game_search' in request.endpoint %}active{% endif %} item">
                            <i class="search icon"></i>
                            {{ _('Пошук ігор') }}</a>
                    {% endif %}
                    {% if 'views.world_rating' in config.BLUEPRINTS %}
                        <a class="{% if '.world_rating' in request.endpoint %}
                            active{% endif %} item"
                           href="{{ url_for('world_rating.rating') }}">
                            <i class="world icon"></i>
                            {{ _('Світовий рейтинг') }}</a>
                    {% endif %}
                    {% if 'views.sparrings' in config.BLUEPRINTS %}
                        <a href="{{ url_for('.sparring') }}"
                           class="{% if   '.sparring' in request.endpoint %}active{% endif %} item">
                            <i class="announcement icon"></i>
                            {{ _('Спаринг оголошення') }}</a>
                    {% endif %}
                    {% if 'views.live_tournaments' in config.BLUEPRINTS %}
                        <div class="divider"></div>
                        <a href="{{ url_for('.live_tournament_home') }}"
                           class="{% if '.live_tournament_home' in request.endpoint %}active{% endif %} item">
                            <i class="sitemap icon"></i>
                            {{ _('Турніри онлайн') }}</a>
                    {% endif %}
                    <div class="divider"></div>
                    <a href="{{ url_for('main.about') }}"
                       class="{% if 'about' in request.endpoint %}active{% endif %} item">
                        <i class="info circle icon"></i>
                        {{ _('Про сайт') }}</a>
                    <div class="divider"></div>
                    <!--language selection-->
                    {% for i, name in config.SUPPORTED_LANGUAGES.items() %}
                        {% if i == g.lang %}
                            <a class="active item"
                               href="{{ request.url.replace('/%s/' % g.lang,'/%s/' % i) }}">
                                {{ name }}</a>
                        {% else %}
                            <a class="item" style="color: darkgrey"
                               href="{{ request.url.replace('/%s/' % g.lang,'/%s/' % i) }}">
                                {{ name }}</a>
                        {% endif %}
                    {% endfor %}
{#                    <div class="divider"></div>#}
{#                    <a class="item"#}
{#                       href="{{ url_for('.change_version',mobile='on',page=request.url) }}">#}
{#                        <i class="mobile icon"></i>#}
{#                        {{ _('Мобільна версія') }}#}
{#                    </a>#}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/pagination.html
{% if pagination.pages > 1 %}
    <div class="ui pagination menu">
        {% for page in pagination.iter_pages() %}
            {% if page %}
                {% if page != pagination.page %}
                    <a class="item"
                       href="{{ url_for_other_page(page) }}">{{ page }}</a>
                {% else %}
                    <strong class="active item">{{ page }}</strong>
                {% endif %}
            {% else %}
                <div class="disabled item">
                    ...
                </div>
            {% endif %}
        {% endfor %}
        {% if pagination.has_next %}
            <a class="icon item"
               href="{{ url_for_other_page(pagination.page + 1) }}"><i
                    class="right chevron icon"></i></a>
        {% endif %}
    </div>
{% endif %}